# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(440, 20, 92, 31))
        self.LoginButton.setObjectName("LoginButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 191, 31))
        self.label.setObjectName("label")
        self.Browser = QtWidgets.QComboBox(self.centralwidget)
        self.Browser.setGeometry(QtCore.QRect(210, 20, 201, 31))
        self.Browser.setObjectName("Browser")
        self.Browser.addItem("")
        self.Browser.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 72, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 121, 31))
        self.label_3.setObjectName("label_3")
        self.ClassName = QtWidgets.QComboBox(self.centralwidget)
        self.ClassName.setGeometry(QtCore.QRect(150, 120, 381, 31))
        self.ClassName.setObjectName("ClassName")
        self.ifCoroutine = QtWidgets.QCheckBox(self.centralwidget)
        self.ifCoroutine.setGeometry(QtCore.QRect(20, 170, 231, 31))
        self.ifCoroutine.setChecked(True)
        self.ifCoroutine.setObjectName("ifCoroutine")
        self.ifAllVideos = QtWidgets.QCheckBox(self.centralwidget)
        self.ifAllVideos.setGeometry(QtCore.QRect(20, 200, 411, 31))
        self.ifAllVideos.setChecked(False)
        self.ifAllVideos.setObjectName("ifAllVideos")
        self.CookieEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CookieEdit.setGeometry(QtCore.QRect(90, 70, 441, 31))
        self.CookieEdit.setReadOnly(True)
        self.CookieEdit.setObjectName("CookieEdit")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(440, 170, 91, 61))
        self.StartButton.setObjectName("StartButton")
        self.Info = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Info.setGeometry(QtCore.QRect(20, 240, 511, 241))
        self.Info.setReadOnly(True)
        self.Info.setCenterOnScroll(True)
        self.Info.setObjectName("Info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "长江雨课堂刷课神器（Author: SleepyCelery）"))
        self.LoginButton.setText(_translate("MainWindow", "登录雨课堂"))
        self.label.setText(_translate("MainWindow", "请选择登录使用的浏览器："))
        self.Browser.setItemText(0, _translate("MainWindow", "Google Chrome"))
        self.Browser.setItemText(1, _translate("MainWindow", "Microsoft Edge"))
        self.label_2.setText(_translate("MainWindow", "Cookie："))
        self.label_3.setText(_translate("MainWindow", "请选择要刷的课："))
        self.ifCoroutine.setText(_translate("MainWindow", "启动心跳协程并发(单视频秒刷)"))
        self.ifAllVideos.setText(_translate("MainWindow", "刷该课程所有视频（不勾选默认只刷一个尚未观看的视频）"))
        self.StartButton.setText(_translate("MainWindow", "开始刷课"))
        self.Info.setPlaceholderText(_translate("MainWindow", "在此处显示程序运行信息"))
